test:
  type: test
  before_script:
    - "pip install -r requirements.txt"
    - "pip install codacy-coverage"
    - "export CODACY_PROJECT_TOKEN=39b902b77813413692bc60f88399e7df"
  cache: ~
  coverage: /^TOTAL.*\s+(\d+\%)$/
  image: "python:3.6"
  script:
    - "echo \"Running unit tests…\""
    - "python manage.py migrate --noinput"
    - "coverage run --source='.' manage.py test"
    - "coverage report"
    - "coverage xml"
    - "python-codacy-coverage -r coverage.xml"

production:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=lms-nsdev --api-key=a201737c-1888-4a15-b5b6-f79c53978c85
  only:
    - master

