# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class Test1SuperUserCreate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_1SuperUserCreate(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.find_element(By.ID, "id_username").send_keys("nsdevil")
    self.driver.find_element(By.ID, "id_password").send_keys("nsdevil")
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    self.driver.find_element(By.LINK_TEXT, "Center infos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
    self.driver.find_element(By.ID, "id_Center_Name").send_keys("KU")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row").click()
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.LINK_TEXT, "Webapp").click()
    self.driver.find_element(By.LINK_TEXT, "Member infos").click()
    self.driver.find_element(By.LINK_TEXT, "1").click()
    self.driver.find_element(By.ID, "id_Center_Code").click()
    dropdown = self.driver.find_element(By.ID, "id_Center_Code")
    dropdown.find_element(By.XPATH, "//option[. = 'KU']").click()
    self.driver.find_element(By.ID, "id_Center_Code").click()
    self.driver.find_element(By.ID, "id_Member_Gender").click()
    dropdown = self.driver.find_element(By.ID, "id_Member_Gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Male']").click()
    self.driver.find_element(By.ID, "id_Member_Gender").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-Is_Parent .vCheckboxLabel").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-Is_CenterAdmin .vCheckboxLabel").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-Is_Student .vCheckboxLabel").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-Is_Teacher .vCheckboxLabel").click()
    self.driver.find_element(By.NAME, "_save").click()
    assert self.driver.title == "Select member info to change | Django site admin"

